package com.fptu.exe.skillswap.modules.notification.domain;

public enum NotificationType {
    MENTOR_VERIFICATION_APPROVED,
    MENTOR_VERIFICATION_REJECTED,
    MENTOR_VERIFICATION_NEEDS_REVISION,
    BOOKING_REQUEST_CREATED,
    BOOKING_ACCEPTED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED_BY_MENTEE,
    BOOKING_CANCELLED_BY_MENTOR,
    BOOKING_AUTO_REJECTED,
    MEETING_LINK_UPDATED,
    SESSION_COMPLETED,
    FEEDBACK_RECEIVED
}
