package com.fptu.exe.skillswap.modules.notification.domain;

public enum NotificationType {
    MENTOR_VERIFICATION_APPROVED,
    MENTOR_VERIFICATION_REJECTED,
    MENTOR_VERIFICATION_NEEDS_REVISION,
    BOOKING_REQUEST_CREATED,
    BOOKING_ACCEPTED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED_BY_MENTEE,
    BOOKING_CANCELLED_BY_MENTOR,
    BOOKING_AUTO_REJECTED,
    BOOKING_REQUEST_EXPIRED,
    BOOKING_RESCHEDULE_REQUESTED,
    BOOKING_RESCHEDULE_ACCEPTED,
    BOOKING_RESCHEDULE_REJECTED,
    BOOKING_RESCHEDULE_EXPIRED,
    MEETING_LINK_UPDATED,
    SESSION_COMPLETED,
    FEEDBACK_RECEIVED,
    FORUM_POST_COMMENTED,
    FORUM_POST_HIDDEN,
    FORUM_COMMENT_HIDDEN,
    ACCOUNT_UNLOCKED
}
