package com.fptu.exe.skillswap.modules.booking.service;

import com.fptu.exe.skillswap.modules.booking.domain.Booking;
import com.fptu.exe.skillswap.modules.booking.domain.CalendarSyncStatus;
import com.fptu.exe.skillswap.modules.booking.domain.MeetingPlatform;
import com.fptu.exe.skillswap.modules.booking.domain.Session;
import com.fptu.exe.skillswap.modules.booking.port.BookingCalendarPort;
import com.fptu.exe.skillswap.modules.booking.repository.BookingRepository;
import com.fptu.exe.skillswap.shared.exception.BaseException;
import com.fptu.exe.skillswap.shared.exception.ErrorCode;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.util.Optional;
import java.util.UUID;

@Service
@RequiredArgsConstructor
class BookingCalendarPortImpl implements BookingCalendarPort {

    private final BookingRepository bookingRepository;
    private final SessionService sessionService;

    @Override
    @Transactional
    public Optional<BookingCalendarSnapshot> findForCalendarSync(UUID bookingId, boolean ensureSession) {
        return bookingRepository.findByIdForSessionUpdate(bookingId).map(booking -> {
            Session session = sessionService.findByBookingId(bookingId);
            if (session == null && ensureSession) {
                session = sessionService.createForAcceptedBooking(booking);
            }
            return snapshot(booking, session);
        });
    }

    @Override
    @Transactional
    public Optional<BookingCalendarSnapshot> refreshSchedule(UUID bookingId) {
        return bookingRepository.findByIdForSessionUpdate(bookingId).map(booking -> {
            Session session = sessionService.findByBookingId(bookingId);
            if (session == null) {
                throw new BaseException(ErrorCode.NOT_FOUND, "Khong tim thay session cua booking");
            }
            session = sessionService.updateScheduleForBooking(bookingId,
                    BookingTime.resolveSelectedStartUtc(booking), BookingTime.resolveSelectedEndUtc(booking));
            return snapshot(booking, session);
        });
    }

    @Override
    @Transactional
    public void updateCalendarState(UUID bookingId, BookingCalendarStateUpdate update) {
        Session session = sessionService.findByBookingId(bookingId);
        if (session == null) return;
        if (update.syncStatus() != null) session.setCalendarSyncStatus(CalendarSyncStatus.valueOf(update.syncStatus()));
        session.setCalendarSyncErrorCode(update.errorCode());
        session.setCalendarSyncErrorMessage(update.errorMessage());
        session.setCalendarLastSyncedAtUtc(update.syncedAtUtc());
        session.setCalendarLastSyncedAt(BookingTime.fromInstant(update.syncedAtUtc()));
        if (update.meetingPlatform() != null) session.setMeetingPlatform(MeetingPlatform.valueOf(update.meetingPlatform()));
        if (update.meetingLink() != null) session.setMeetingLink(update.meetingLink());
        if (update.googleCalendarManaged() != null) session.setGoogleCalendarManaged(update.googleCalendarManaged());
        if (update.googleMeetAutoGenerated() != null) session.setGoogleMeetAutoGenerated(update.googleMeetAutoGenerated());
        sessionService.save(session);
    }

    private BookingCalendarSnapshot snapshot(Booking booking, Session session) {
        Instant start = session == null ? BookingTime.resolveSelectedStartUtc(booking) : session.getScheduledStartTimeUtc();
        Instant end = session == null ? BookingTime.resolveSelectedEndUtc(booking) : session.getScheduledEndTimeUtc();
        MeetingPlatform platform = session != null && session.getMeetingPlatform() != null
                ? session.getMeetingPlatform() : booking.getMeetingPlatform();
        String link = session != null && session.getMeetingLink() != null ? session.getMeetingLink() : booking.getMeetingLink();
        return new BookingCalendarSnapshot(booking.getId(), session == null ? null : session.getId(),
                booking.getMentorUserId(), booking.getMenteeUserId(), booking.getServiceTitleSnapshot(),
                booking.getLearningGoalTitle(), booking.getLearningGoalDescription(), booking.getLocation(), start, end,
                platform == null ? null : platform.name(), link,
                session != null && session.isGoogleCalendarManaged(), session != null && session.isGoogleMeetAutoGenerated());
    }
}
