package com.fptu.exe.skillswap.modules.identity.service;

import com.fptu.exe.skillswap.modules.booking.port.BookingCalendarPort;
import com.fptu.exe.skillswap.modules.booking.port.BookingCalendarPort.BookingCalendarSnapshot;
import com.fptu.exe.skillswap.modules.booking.port.BookingCalendarPort.BookingCalendarStateUpdate;
import com.fptu.exe.skillswap.modules.identity.domain.*;
import com.fptu.exe.skillswap.modules.identity.event.*;
import com.fptu.exe.skillswap.modules.identity.repository.*;
import com.fptu.exe.skillswap.shared.exception.*;
import com.fptu.exe.skillswap.shared.time.BusinessTime;
import com.fptu.exe.skillswap.shared.time.TimeProvider;
import lombok.RequiredArgsConstructor;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.*;
import java.util.*;

@Service @RequiredArgsConstructor
public class GoogleCalendarSyncService {
    private static final List<Long> RETRIES = List.of(1L,5L,15L,30L,60L,180L,360L,720L);
    private final GoogleCalendarSyncJobRepository jobs;
    private final GoogleCalendarEventLinkRepository links;
    private final BookingCalendarPort calendar;
    private final GoogleCalendarConnectionService connections;
    private final GoogleCalendarConnectionRepository connectionRepository;
    private final GoogleCalendarApiClient api;
    private final ApplicationEventPublisher events;
    private final org.springframework.transaction.support.TransactionTemplate tx;
    private final TimeProvider clock;
    @Transactional public void enqueueCreate(UUID id){enqueue(id,GoogleCalendarSyncJobType.CREATE_BOOKING_EVENT,"BOOKING_CREATE:"+id);}
    @Transactional public void enqueueUpdate(UUID id,Instant at){enqueue(id,GoogleCalendarSyncJobType.UPDATE_BOOKING_EVENT,"BOOKING_UPDATE:"+id+":"+(at==null?"unknown":at));}
    @Transactional public void enqueueCancel(UUID id){enqueue(id,GoogleCalendarSyncJobType.CANCEL_BOOKING_EVENT,"BOOKING_CANCEL:"+id);}
    public void processDueJobs(){Instant now=clock.instant();List<UUID> ids=tx.execute(x->jobs.findTop20RunnableForUpdateUtc(List.of(GoogleCalendarSyncJobStatus.PENDING,GoogleCalendarSyncJobStatus.RETRYING),now,BusinessTime.fromInstant(now),PageRequest.of(0,20)).stream().map(GoogleCalendarSyncJob::getId).toList());if(ids!=null)ids.forEach(this::processSingleJob);}
    public void processSingleJob(UUID id){Instant now=clock.instant();boolean claimed=Boolean.TRUE.equals(tx.execute(x->jobs.claimForProcessingUtc(id,List.of(GoogleCalendarSyncJobStatus.PENDING,GoogleCalendarSyncJobStatus.RETRYING),GoogleCalendarSyncJobStatus.PROCESSING,now,BusinessTime.fromInstant(now))==1));if(!claimed)return;GoogleCalendarSyncJob job=jobs.findById(id).orElse(null);if(job==null)return;BookingCalendarSnapshot s=null;try{s=calendar.findForCalendarSync(job.getBookingId(),job.getJobType()!=GoogleCalendarSyncJobType.CANCEL_BOOKING_EVENT).orElseThrow(()->new BaseException(ErrorCode.NOT_FOUND,"Calendar booking was not found"));switch(job.getJobType()){case CREATE_BOOKING_EVENT->create(job,s);case UPDATE_BOOKING_EVENT->update(job,s);case CANCEL_BOOKING_EVENT->cancel(job,s);}complete(job);}catch(GoogleCalendarApiClient.GoogleCalendarTransientException e){retry(job,s,e.getErrorCode(),e.getMessage());}catch(GoogleCalendarApiClient.GoogleCalendarApiException|BaseException e){String code=e instanceof GoogleCalendarApiClient.GoogleCalendarApiException a?a.getErrorCode():((BaseException)e).getErrorCode().getCode();fail(job,s,code,e.getMessage());}catch(Exception e){fail(job,s,"INTERNAL_ERROR",e.getMessage());}}
    private void create(GoogleCalendarSyncJob j,BookingCalendarSnapshot s){requireSession(s);if(near(j,s)){abort(j,s);return;}GoogleCalendarConnection c=connections.getActiveConnectionForSync(j.getMentorUserId());if(c==null){state(s,"NOT_CONNECTED",null,null,null,null,false,false);return;}if(c.getConnectionStatus()==GoogleCalendarConnectionStatus.REVOKED){revoked(j,s,c);return;}GoogleCalendarEventLink link=links.findByBookingId(s.bookingId()).orElse(null);if(link!=null){synced(s,c,link.getGoogleMeetUrl());return;}var r=api.createBookingEvent(connections.resolveAccessTokenForSync(c.getId()),c.getCalendarId(),"booking-"+s.bookingId(),s);String meet=manual(s)?s.meetingLink():r.googleMeetUrl();links.save(GoogleCalendarEventLink.builder().bookingId(s.bookingId()).sessionId(s.sessionId()).mentorUserId(j.getMentorUserId()).googleEventId(r.eventId()).googleMeetUrl(meet).etag(r.etag()).eventStatus(GoogleCalendarEventStatus.ACTIVE).build());synced(s,c,meet);}
    private void update(GoogleCalendarSyncJob j,BookingCalendarSnapshot ignored){BookingCalendarSnapshot s=calendar.refreshSchedule(j.getBookingId()).orElseThrow();if(near(j,s)){abort(j,s);return;}GoogleCalendarEventLink link=links.findByBookingId(s.bookingId()).orElse(null);if(link==null){create(j,s);return;}GoogleCalendarConnection c=connections.getActiveConnectionForSync(j.getMentorUserId());if(c==null){state(s,"NOT_CONNECTED",null,null,null,null,false,false);return;}if(c.getConnectionStatus()==GoogleCalendarConnectionStatus.REVOKED){revoked(j,s,c);return;}var r=api.updateBookingEvent(connections.resolveAccessTokenForSync(c.getId()),c.getCalendarId(),link.getGoogleEventId(),s);link.setEtag(r.etag());if(!manual(s)&&r.googleMeetUrl()!=null)link.setGoogleMeetUrl(r.googleMeetUrl());link.setEventStatus(GoogleCalendarEventStatus.ACTIVE);links.save(link);synced(s,c,link.getGoogleMeetUrl());}
    private void cancel(GoogleCalendarSyncJob j,BookingCalendarSnapshot s){GoogleCalendarEventLink link=links.findByBookingId(s.bookingId()).orElse(null);if(link==null){state(s,"CANCELLED",null,null,null,null,null,null);return;}GoogleCalendarConnection c=connections.getActiveConnectionForSync(j.getMentorUserId());if(c!=null&&c.getConnectionStatus()!=GoogleCalendarConnectionStatus.REVOKED)api.cancelBookingEvent(connections.resolveAccessTokenForSync(c.getId()),c.getCalendarId(),link.getGoogleEventId());link.setEventStatus(GoogleCalendarEventStatus.CANCELLED);link.setLastErrorCode(null);link.setLastErrorMessage(null);links.save(link);state(s,"CANCELLED",null,null,null,null,null,null);}
    private void retry(GoogleCalendarSyncJob j,BookingCalendarSnapshot s,String code,String msg){if(s==null||near(j,s)||j.getAttemptCount()>=RETRIES.size()){fail(j,s,code,msg);return;}Instant at=clock.instant().plus(Duration.ofMinutes(RETRIES.get(j.getAttemptCount())));j.setAttemptCount(j.getAttemptCount()+1);j.setStatus(GoogleCalendarSyncJobStatus.RETRYING);j.setRunAfterUtc(at);j.setRunAfter(BusinessTime.fromInstant(at));j.setLastErrorCode(code);j.setLastErrorMessage(msg);jobs.save(j);state(s,"PENDING_SYNC",code,msg,null,null,null,null);}
    private void fail(GoogleCalendarSyncJob j,BookingCalendarSnapshot s,String code,String msg){Instant now=clock.instant();j.setStatus(GoogleCalendarSyncJobStatus.FAILED);j.setCompletedAtUtc(now);j.setCompletedAt(BusinessTime.fromInstant(now));j.setLastErrorCode(code);j.setLastErrorMessage(msg);jobs.save(j);if(s!=null){state(s,"SYNC_ERROR",code,msg,null,null,null,null);events.publishEvent(new CalendarSyncFailedEvent(s.bookingId(),s.mentorUserId(),s.menteeUserId(),code,msg));}}
    private void abort(GoogleCalendarSyncJob j,BookingCalendarSnapshot s){Instant now=clock.instant();j.setStatus(GoogleCalendarSyncJobStatus.ABORTED);j.setCompletedAtUtc(now);j.setCompletedAt(BusinessTime.fromInstant(now));j.setLastErrorCode("GOOGLE_CALENDAR_EXPIRED_SYNC");jobs.save(j);state(s,"EXPIRED_SYNC","GOOGLE_CALENDAR_EXPIRED_SYNC","Calendar synchronization was too close to start time",null,null,null,null);events.publishEvent(new CalendarSyncAbortedNearStartTimeEvent(s.bookingId(),s.mentorUserId(),s.menteeUserId()));}
    private void revoked(GoogleCalendarSyncJob j,BookingCalendarSnapshot s,GoogleCalendarConnection c){fail(j,s,"GOOGLE_CALENDAR_REVOKED","Mentor revoked Google Calendar access");c.setLastSyncStatus(GoogleCalendarSyncStatus.REVOKED);connectionRepository.save(c);events.publishEvent(new CalendarSyncConnectionRevokedEvent(s.bookingId(),s.mentorUserId(),s.menteeUserId()));}
    private void synced(BookingCalendarSnapshot s,GoogleCalendarConnection c,String meet){state(s,"SYNCED",null,null,manual(s)?null:"GOOGLE_MEET",manual(s)?null:meet,manual(s)?null:true,manual(s)?null:true);Instant now=clock.instant();c.setLastSyncStatus(GoogleCalendarSyncStatus.SYNCED);c.setLastSyncAtUtc(now);c.setLastSyncAt(BusinessTime.fromInstant(now));c.setLastSyncErrorCode(null);c.setLastSyncErrorMessage(null);connectionRepository.save(c);}
    private void state(BookingCalendarSnapshot s,String status,String code,String msg,String platform,String link,Boolean managed,Boolean generated){calendar.updateCalendarState(s.bookingId(),new BookingCalendarStateUpdate(status,code,msg,clock.instant(),platform,link,managed,generated));}
    private boolean manual(BookingCalendarSnapshot s){return !s.googleCalendarManaged()||(s.meetingPlatform()!=null&&!"GOOGLE_MEET".equals(s.meetingPlatform()));}
    private boolean near(GoogleCalendarSyncJob j,BookingCalendarSnapshot s){return j.getJobType()!=GoogleCalendarSyncJobType.CANCEL_BOOKING_EVENT&&s.startUtc()!=null&&!clock.instant().isBefore(s.startUtc().minus(Duration.ofMinutes(15)));}
    private void requireSession(BookingCalendarSnapshot s){if(s.sessionId()==null)throw new BaseException(ErrorCode.RESOURCE_CONFLICT,"Booking has no session for calendar sync");}
    private void complete(GoogleCalendarSyncJob j){if(j.getStatus()==GoogleCalendarSyncJobStatus.PROCESSING){Instant now=clock.instant();j.setStatus(GoogleCalendarSyncJobStatus.SUCCEEDED);j.setCompletedAtUtc(now);j.setCompletedAt(BusinessTime.fromInstant(now));j.setLastErrorCode(null);j.setLastErrorMessage(null);jobs.save(j);}}
    private void enqueue(UUID id,GoogleCalendarSyncJobType type,String key){if(jobs.findByIdempotencyKey(key).isPresent())return;BookingCalendarSnapshot s=calendar.findForCalendarSync(id,false).orElseThrow(()->new BaseException(ErrorCode.NOT_FOUND,"Calendar booking was not found"));Instant now=clock.instant();jobs.save(GoogleCalendarSyncJob.builder().bookingId(id).sessionId(s.sessionId()).mentorUserId(s.mentorUserId()).jobType(type).status(GoogleCalendarSyncJobStatus.PENDING).attemptCount(0).runAfterUtc(now).runAfter(BusinessTime.fromInstant(now)).idempotencyKey(key).build());if(s.sessionId()!=null)state(s,"PENDING_SYNC",null,null,null,null,null,null);}
}
