package com.fptu.exe.skillswap.modules.booking.port;

import java.time.Instant;
import java.util.Optional;
import java.util.UUID;

/** Public calendar integration contract. Implementations retain all Booking and Session persistence details. */
public interface BookingCalendarPort {

    Optional<BookingCalendarSnapshot> findForCalendarSync(UUID bookingId, boolean ensureSession);

    Optional<BookingCalendarSnapshot> refreshSchedule(UUID bookingId);

    void updateCalendarState(UUID bookingId, BookingCalendarStateUpdate update);

    record BookingCalendarSnapshot(
            UUID bookingId,
            UUID sessionId,
            UUID mentorUserId,
            UUID menteeUserId,
            String serviceTitle,
            String learningGoalTitle,
            String learningGoalDescription,
            String location,
            Instant startUtc,
            Instant endUtc,
            String meetingPlatform,
            String meetingLink,
            boolean googleCalendarManaged,
            boolean googleMeetAutoGenerated
    ) {}

    record BookingCalendarStateUpdate(
            String syncStatus,
            String errorCode,
            String errorMessage,
            Instant syncedAtUtc,
            String meetingPlatform,
            String meetingLink,
            Boolean googleCalendarManaged,
            Boolean googleMeetAutoGenerated
    ) {}
}
