package com.fptu.exe.skillswap.modules.booking.domain;

/** Business and financial transitions only; this is not an activity log. */
public enum BookingEventType {
    BOOKING_CREATED,
    MENTOR_ACCEPTED,
    PAYMENT_CONFIRMED,
    POST_SESSION_STARTED,
    MENTOR_COMPLETED,
    MENTEE_CONFIRMED,
    ISSUE_CREATED,
    ISSUE_RESPONDED,
    ISSUE_ESCALATED_TO_ADMIN,
    ADMIN_SLA_OVERDUE,
    ADMIN_SLA_REMINDER_SENT,
    ADMIN_SLA_AUTO_RELEASED,
    ISSUE_RESOLVED,
    ISSUE_RESOLUTION_REVERSED,
    MENTOR_COMPLETION_OVERDUE,
    AUTO_CLOSED,
    SETTLEMENT_RELEASED,
    REFUND_EXECUTED,
    ADMIN_SLA_WARNING_SENT
}

