package com.fptu.exe.skillswap.modules.booking.domain;

import com.fptu.exe.skillswap.shared.time.BusinessTime;
import com.fptu.exe.skillswap.shared.persistence.GeneratedUuidV7;
import com.fptu.exe.skillswap.shared.util.DateTimeUtil;
import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;
import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(name = "sessions", indexes = {
    @Index(name = "idx_sessions_source", columnList = "source_type, source_id", unique = true),
    @Index(name = "idx_sessions_mentor_id", columnList = "mentor_user_id"),
    @Index(name = "idx_sessions_status", columnList = "status")
})
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Session {

    @Id
    @GeneratedUuidV7
    private UUID id;

    /** Immutable reference to the service selected when this booking was accepted. */
    @Column(name = "service_id")
    private UUID serviceId;

    @Column(name = "mentor_user_id", nullable = false)
    private UUID mentorUserId;

    @Enumerated(EnumType.STRING)
    @Column(name = "source_type", nullable = false, length = 50)
    private SessionSourceType sourceType;

    @Column(name = "source_id", nullable = false)
    private UUID sourceId;

    @Column(name = "scheduled_start_time_utc", nullable = false)
    private Instant scheduledStartTimeUtc;

    @Deprecated
    @Column(name = "scheduled_start_time", nullable = false)
    private LocalDateTime scheduledStartTime;

    @Column(name = "scheduled_end_time_utc", nullable = false)
    private Instant scheduledEndTimeUtc;

    @Deprecated
    @Column(name = "scheduled_end_time", nullable = false)
    private LocalDateTime scheduledEndTime;

    @Column(name = "actual_start_time_utc")
    private Instant actualStartTimeUtc;

    @Deprecated
    @Column(name = "actual_start_time")
    private LocalDateTime actualStartTime;

    @Column(name = "actual_end_time_utc")
    private Instant actualEndTimeUtc;

    @Deprecated
    @Column(name = "actual_end_time")
    private LocalDateTime actualEndTime;

    @Enumerated(EnumType.STRING)
    @Column(name = "meeting_platform")
    private MeetingPlatform meetingPlatform;

    @Column(name = "meeting_link", columnDefinition = "TEXT")
    private String meetingLink;

    @Column(name = "google_calendar_managed", nullable = false)
    @Builder.Default
    private boolean googleCalendarManaged = false;

    @Column(name = "google_meet_auto_generated", nullable = false)
    @Builder.Default
    private boolean googleMeetAutoGenerated = false;

    @Enumerated(EnumType.STRING)
    @Column(name = "calendar_sync_status", length = 50)
    private CalendarSyncStatus calendarSyncStatus;

    @Column(name = "calendar_sync_error_code", length = 100)
    private String calendarSyncErrorCode;

    @Column(name = "calendar_sync_error_message", columnDefinition = "TEXT")
    private String calendarSyncErrorMessage;

    @Column(name = "calendar_last_synced_at_utc")
    private Instant calendarLastSyncedAtUtc;

    @Deprecated
    @Column(name = "calendar_last_synced_at")
    private LocalDateTime calendarLastSyncedAt;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 50)
    @Builder.Default
    private SessionStatus status = SessionStatus.SCHEDULED;

    @Column(name = "created_at_utc", nullable = false, updatable = false)
    private Instant createdAtUtc;

    @Deprecated
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at_utc", nullable = false)
    private Instant updatedAtUtc;

    @Deprecated
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    public void onCreate() {
        syncTimestampPairs();
        Instant nowUtc = DateTimeUtil.instantNow();
        if (createdAtUtc == null) createdAtUtc = nowUtc;
        if (createdAt == null) createdAt = BusinessTime.fromInstant(createdAtUtc);
        if (updatedAtUtc == null) updatedAtUtc = nowUtc;
        if (updatedAt == null) updatedAt = BusinessTime.fromInstant(updatedAtUtc);
    }

    @PreUpdate
    public void onUpdate() {
        syncTimestampPairs();
        updatedAtUtc = DateTimeUtil.instantNow();
        updatedAt = BusinessTime.fromInstant(updatedAtUtc);
    }

    private void syncTimestampPairs() {
        if (scheduledStartTimeUtc == null) scheduledStartTimeUtc = BusinessTime.toInstant(scheduledStartTime); else if (scheduledStartTime == null) scheduledStartTime = BusinessTime.fromInstant(scheduledStartTimeUtc);
        if (scheduledEndTimeUtc == null) scheduledEndTimeUtc = BusinessTime.toInstant(scheduledEndTime); else if (scheduledEndTime == null) scheduledEndTime = BusinessTime.fromInstant(scheduledEndTimeUtc);
        if (actualStartTimeUtc == null) actualStartTimeUtc = BusinessTime.toInstant(actualStartTime); else if (actualStartTime == null) actualStartTime = BusinessTime.fromInstant(actualStartTimeUtc);
        if (actualEndTimeUtc == null) actualEndTimeUtc = BusinessTime.toInstant(actualEndTime); else if (actualEndTime == null) actualEndTime = BusinessTime.fromInstant(actualEndTimeUtc);
        if (calendarLastSyncedAtUtc == null) calendarLastSyncedAtUtc = BusinessTime.toInstant(calendarLastSyncedAt); else if (calendarLastSyncedAt == null) calendarLastSyncedAt = BusinessTime.fromInstant(calendarLastSyncedAtUtc);
    }
}
