package com.fptu.exe.skillswap.modules.forum.domain;

public enum ForumActionType {
    CREATE_POST,
    CREATE_COMMENT,
    CREATE_REPORT,
    TOGGLE_REACTION,
    DELETE_POST,
    DELETE_COMMENT,
    ADMIN_HIDE_POST,
    ADMIN_HIDE_COMMENT,
    ADMIN_RESTORE_POST,
    ADMIN_RESTORE_COMMENT,
    ADMIN_CONFIRM_NO_ACTION,
    ADMIN_DISMISS_REPORT
}
