-- rollout: EXPAND
-- Keep the notification type constraint aligned with the application contract.
ALTER TABLE notifications DROP CONSTRAINT IF EXISTS notifications_type_check;

ALTER TABLE notifications
    ADD CONSTRAINT notifications_type_check
        CHECK (type IN (
            'MENTOR_VERIFICATION_APPROVED', 'MENTOR_VERIFICATION_REJECTED', 'MENTOR_VERIFICATION_NEEDS_REVISION',
            'BOOKING_REQUEST_CREATED', 'BOOKING_ACCEPTED', 'BOOKING_PAYMENT_CONFIRMED', 'BOOKING_PAYMENT_EXPIRED',
            'BOOKING_REJECTED', 'BOOKING_CANCELLED_BY_MENTEE', 'BOOKING_CANCELLED_BY_MENTOR', 'BOOKING_AUTO_REJECTED',
            'BOOKING_REQUEST_EXPIRED', 'BOOKING_RESCHEDULE_REQUESTED', 'BOOKING_RESCHEDULE_ACCEPTED',
            'BOOKING_RESCHEDULE_REJECTED', 'BOOKING_RESCHEDULE_EXPIRED', 'MEETING_LINK_UPDATED',
            'GOOGLE_CALENDAR_SYNC_NOTICE', 'SESSION_COMPLETED', 'BOOKING_ISSUE_REPORTED',
            'BOOKING_ISSUE_RESPONSE_RECEIVED', 'BOOKING_ISSUE_RESPONSE_REMINDER', 'BOOKING_ISSUE_RESOLVED',
            'BOOKING_ISSUE_ADMIN_REVIEW_REQUIRED', 'BOOKING_REMINDER', 'FEEDBACK_PROMPT', 'FEEDBACK_RECEIVED',
            'FORUM_POST_COMMENTED', 'FORUM_COMMENT_REPLY', 'FORUM_POST_HIDDEN', 'FORUM_COMMENT_HIDDEN',
            'BLOG_POST_PUBLISHED', 'CHAT_UNREAD', 'ACCOUNT_UNLOCKED', 'ADMIN_DISPUTE_SLA_BREACH',
            'BOOKING_ISSUE_RESOLUTION_REVERSED', 'COURSE_ANNOUNCEMENT'
        ));

-- One announcement produces at most one notification for a given recipient.
CREATE UNIQUE INDEX IF NOT EXISTS uk_notifications_course_announcement_recipient
    ON notifications (recipient_user_id, related_entity_type, related_entity_id)
    WHERE related_entity_type = 'COURSE_ANNOUNCEMENT' AND related_entity_id IS NOT NULL;
