-- Baseline schema generated from the current JPA model and adjusted to preserve incremental Flyway compatibility.
-- Purpose: allow fresh PostgreSQL databases to start from V1, then continue with V2+ safely.
-- Notes:
-- 1. Legacy pricing columns are intentionally kept so V23 can backfill SCoin fields without failing.
-- 2. PostgreSQL-specific safety constraints or indexes introduced later remain in later migrations.

create table academic_programs (is_active boolean not null, id uuid not null, code varchar(30) not null unique, name_en varchar(150), name_vi varchar(150) not null, primary key (id));
create table admin_notes (created_at timestamp(6) not null, admin_user_id uuid not null, id uuid not null, target_id uuid not null, target_type varchar(80) not null, note TEXT not null, primary key (id));
create table audit_logs (created_at timestamp(6) not null, actor_user_id uuid, entity_id uuid, id uuid not null, entity_type varchar(80) not null, ip_address varchar(100), action varchar(255) not null check (action in ('CREATE','UPDATE','DELETE','APPROVE','REJECT','LOGIN','LOGOUT','EXPORT')), new_value jsonb, old_value jsonb, user_agent TEXT, primary key (id));
create table availability_slot_services (created_at timestamp(6), service_id uuid not null, slot_id uuid not null, primary key (service_id, slot_id));
create table bookings (service_duration_snapshot integer, service_is_free_snapshot boolean, service_price_amount_snapshot numeric(12,2), service_currency_snapshot varchar(10), service_price_scoin_snapshot integer, wants_admin_review boolean, accepted_at timestamp(6), actual_end_time timestamp(6), actual_start_time timestamp(6), auto_closed_at timestamp(6), cancelled_at timestamp(6), completed_at timestamp(6), created_at timestamp(6) not null, finalized_at timestamp(6), issue_submitted_at timestamp(6), rejected_at timestamp(6), requested_end_time timestamp(6), requested_start_time timestamp(6), selected_end_time timestamp(6), selected_start_time timestamp(6), updated_at timestamp(6) not null, id uuid not null, mentee_user_id uuid not null, mentor_user_id uuid not null, service_id uuid, slot_id uuid, learning_goal_title varchar(200) not null, service_title_snapshot varchar(200), cancel_reason TEXT, completion_outcome varchar(255) check (completion_outcome in ('COMPLETED_CONFIRMED','COMPLETED_AUTO_CLOSED','REVIEW_PENDING_DECISION')), issue_description TEXT, issue_type varchar(255) check (issue_type in ('NO_SHOW_OR_QUALITY_OR_OTHER')), learning_goal_description TEXT, location TEXT, meeting_link TEXT, meeting_platform varchar(255) check (meeting_platform in ('GOOGLE_MEET','ZOOM','MICROSOFT_TEAMS','DISCORD','OFFLINE','OTHER')), mentee_note TEXT, mentor_note TEXT, mentor_response_note TEXT, reject_reason TEXT, service_description_snapshot TEXT, service_expected_outcome_snapshot TEXT, status varchar(255) not null check (status in ('PENDING','ACCEPTED_AWAITING_PAYMENT','ACCEPTED','PAID','REJECTED','EXPIRED','CANCELLED_BY_MENTEE','CANCELLED_BY_MENTOR','AWAITING_MENTOR_COMPLETION','AWAITING_MENTEE_CONFIRMATION','COMPLETED','AUTO_CLOSED','UNDER_REVIEW','NO_SHOW')), primary key (id));
create table campaign_audience_campus_ids (campaign_id uuid not null, campus_id uuid not null, primary key (campaign_id, campus_id));
create table campaign_audience_help_topic_ids (campaign_id uuid not null, help_topic_id uuid not null, primary key (campaign_id, help_topic_id));
create table campaign_audience_program_ids (campaign_id uuid not null, program_id uuid not null, primary key (campaign_id, program_id));
create table campaign_audience_role_codes (campaign_id uuid not null, role_code varchar(40) not null, primary key (campaign_id, role_code));
create table campaign_audience_specialization_ids (campaign_id uuid not null, specialization_id uuid not null, primary key (campaign_id, specialization_id));
create table campaign_benefits (active boolean not null, coupon_discount_value integer, coupon_max_discount_scoin integer, coupon_min_order_value_scoin integer, coupon_quota_per_user integer, coupon_quota_total integer, credit_scoin integer, created_at timestamp(6) not null, updated_at timestamp(6) not null, campaign_id uuid not null, id uuid not null, coupon_discount_type varchar(20) check (coupon_discount_type in ('FIXED','PERCENT')), benefit_type varchar(30) not null check (benefit_type in ('CREDIT_ISSUANCE','COUPON_ISSUANCE')), coupon_code varchar(80), primary key (id));
create table campaigns (budget_scoin integer not null, created_at timestamp(6) not null, end_at timestamp(6), start_at timestamp(6), updated_at timestamp(6) not null, id uuid not null, status varchar(20) not null check (status in ('DRAFT','ACTIVE','PAUSED','ENDED')), funding_source varchar(30) not null check (funding_source in ('APP_FUNDED','MENTOR_FUNDED','MIXED')), name varchar(150) not null, description TEXT, primary key (id));
create table campuses (is_active boolean not null, id uuid not null, city varchar(100), name varchar(100) not null, code varchar(255) not null unique check (code in ('HCM','HA_NOI','DA_NANG','CAN_THO','QUY_NHON','ONLINE')), primary key (id));
create table conversation_participants (joined_at timestamp(6) not null, conversation_id uuid not null, id uuid not null, user_id uuid not null, primary key (id), constraint uq_conv_participant unique (conversation_id, user_id));
create table conversations (created_at timestamp(6) not null, last_message_at timestamp(6), lock_at timestamp(6), updated_at timestamp(6) not null, id uuid not null, source_id uuid not null, source_type varchar(50) not null check (source_type in ('BOOKING','CLASS_OFFERING')), status varchar(50) not null check (status in ('ACTIVE','LOCKED')), type varchar(50) not null check (type in ('DIRECT','GROUP')), last_message_content varchar(1000), primary key (id), constraint idx_conversations_source unique (source_type, source_id));
create table coupon_applicable_help_topic_ids (coupon_id uuid not null, help_topic_id uuid not null, primary key (coupon_id, help_topic_id));
create table coupon_applicable_mentor_ids (coupon_id uuid not null, mentor_user_id uuid not null, primary key (coupon_id, mentor_user_id));
create table coupon_applicable_service_ids (coupon_id uuid not null, service_id uuid not null, primary key (coupon_id, service_id));
create table coupon_redemptions (discount_scoin integer not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, coupon_id uuid not null, id uuid not null, payment_order_id uuid not null unique, redeemer_user_id uuid not null, status varchar(20) not null check (status in ('RESERVED','REDEEMED','VOIDED')), primary key (id));
create table coupons (discount_value integer not null, max_discount_scoin integer, min_order_value_scoin integer, quota_per_user integer, quota_total integer, created_at timestamp(6) not null, end_at timestamp(6), start_at timestamp(6), updated_at timestamp(6) not null, id uuid not null, discount_type varchar(20) not null check (discount_type in ('FIXED','PERCENT')), status varchar(20) not null check (status in ('ACTIVE','INACTIVE','EXPIRED','SUSPENDED')), code varchar(80) not null unique, title varchar(150) not null, description TEXT, primary key (id));
create table credit_ledger_accounts (active boolean not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, id uuid not null, owner_id uuid, owner_type varchar(40) not null check (owner_type in ('USER_CREDIT','MENTOR_SETTLEMENT','PLATFORM_SETTLEMENT')), account_code varchar(120) not null unique, primary key (id), constraint idx_credit_accounts_owner unique (owner_type, owner_id));
create table credit_ledger_entries (amount_scoin integer not null, balance_effect_scoin integer not null, created_at timestamp(6) not null, account_id uuid not null, id uuid not null, source_id uuid, entry_type varchar(30) not null check (entry_type in ('ISSUE','RESERVE','CONSUME','RELEASE','REFUND','ADJUSTMENT','HOLD','PAID_OUT','COMMISSION','VOID')), origin_type varchar(40) not null check (origin_type in ('CAMPAIGN_BONUS','COUPON_BONUS','REFUND','MANUAL','PAYMENT_RESERVATION')), source_type varchar(40) not null check (source_type in ('PAYMENT_ORDER','BOOKING','CAMPAIGN','COUPON','MANUAL','PAYOUT_REQUEST','REFUND')), memo TEXT, primary key (id));
create table email_outbox (retry_count integer not null, created_at timestamp(6) not null, sent_at timestamp(6), id uuid not null, template_code varchar(100), body TEXT not null, last_error TEXT, status varchar(255) not null check (status in ('PENDING','SENT','FAILED','READ')), subject varchar(255) not null, to_email varchar(255) not null, primary key (id));
create table files (created_at timestamp(6) not null, deleted_at timestamp(6), size_bytes bigint, id uuid not null, owner_id uuid not null, storage_provider varchar(50) not null, mime_type varchar(100), checksum varchar(255), original_name varchar(255), public_url TEXT, purpose varchar(255) not null check (purpose in ('AVATAR','VERIFICATION_DOCUMENT','CERTIFICATE','PORTFOLIO','SESSION_ATTACHMENT','FORUM_ATTACHMENT','OTHER')), storage_key TEXT not null, primary key (id));
create table mentor_availability_rules (effective_from date not null, effective_to date, end_time time(6), is_active boolean not null, start_time time(6), created_at timestamp(6) not null, updated_at timestamp(6) not null, id uuid not null, mentor_user_id uuid not null, repeat_type varchar(20) not null check (repeat_type in ('NONE','DAILY','WEEKLY')), rule_type varchar(20) not null check (rule_type in ('OPEN','CLOSED')), days_of_week varchar(80), timezone varchar(80) not null, note varchar(200), primary key (id));
create table mentor_availability_slots (is_active boolean not null, is_booked boolean not null, created_at timestamp(6) not null, end_time timestamp(6) not null, start_time timestamp(6) not null, updated_at timestamp(6) not null, id uuid not null, mentor_user_id uuid not null, rule_id uuid not null, timezone varchar(80) not null, recurrence_rule TEXT, primary key (id));
create table mentor_payout_profiles (is_active boolean not null, is_default boolean not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, id uuid not null, mentor_user_id uuid not null, account_number varchar(50) not null, bank_code varchar(50), account_holder_name varchar(150) not null, bank_name varchar(150) not null, primary key (id));
create table mentor_profiles (average_rating numeric(3,2) not null, is_available boolean not null, late_cancellation_penalty_points numeric(6,2) not null, session_duration integer not null, total_completed_sessions integer not null, total_rejected_bookings integer not null, total_reviews integer not null, total_sessions integer not null, booking_suspended_until timestamp(6), created_at timestamp(6) not null, updated_at timestamp(6) not null, verified_at timestamp(6), user_id uuid not null, verified_by uuid, phone_number varchar(20), teaching_mode varchar(20) check (teaching_mode in ('ONLINE','OFFLINE','HYBRID')), headline varchar(200), expertise_description TEXT, github_url TEXT, linkedin_url TEXT, portfolio_url TEXT, status varchar(255) not null check (status in ('DRAFT','PENDING_VERIFICATION','ACTIVE','PAUSED','REJECTED','SUSPENDED')), supporting_subjects TEXT, primary key (user_id));
create table mentor_service_help_topics (service_id uuid not null, tag_id uuid not null, primary key (service_id, tag_id));
create table mentor_services (duration_minutes integer not null, is_active boolean not null, is_free boolean not null, is_legacy boolean not null, price_amount numeric(12,2) not null default 0, currency varchar(10) not null default 'VND', price_scoin integer not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, id uuid not null, mentor_user_id uuid not null, title varchar(200) not null, description TEXT, expected_outcome TEXT, primary key (id));
create table mentor_tags (is_primary boolean not null, mentor_user_id uuid not null, tag_id uuid not null, tag_type varchar(30) not null check (tag_type in ('EXPERTISE','HELP_TOPIC')), primary key (mentor_user_id, tag_id, tag_type));
create table mentor_verification_documents (is_active boolean not null, version integer not null, updated_at timestamp(6) not null, uploaded_at timestamp(6) not null, id uuid not null, request_id uuid not null, stored_file_id uuid not null, uploaded_by_user_id uuid not null, status varchar(20) not null check (status in ('UPLOADED','ACCEPTED','REJECTED','REMOVED')), storage_kind varchar(20) not null check (storage_kind in ('IMAGE','DOCUMENT')), document_type varchar(40) not null check (document_type in ('FPTU_AFFILIATION_PROOF','EXPERTISE_PROOF')), rejected_reason TEXT, review_note TEXT, primary key (id));
create table mentor_verification_request_events (created_at timestamp(6) not null, actor_user_id uuid, id uuid not null, request_id uuid not null, event_type varchar(255) not null check (event_type in ('REQUEST_CREATED','SUBMITTED','REVISION_REQUESTED','RESUBMITTED','APPROVED','REJECTED','WITHDRAWN')), from_status varchar(255) check (from_status in ('DRAFT','PENDING_REVIEW','NEEDS_REVISION','APPROVED','REJECTED','WITHDRAWN')), note TEXT, to_status varchar(255) check (to_status in ('DRAFT','PENDING_REVIEW','NEEDS_REVISION','APPROVED','REJECTED','WITHDRAWN')), primary key (id));
create table mentor_verification_requests (revision_count integer not null, approved_at timestamp(6), created_at timestamp(6) not null, lock_expires_at timestamp(6), locked_at timestamp(6), reviewed_at timestamp(6), submitted_at timestamp(6), terms_accepted_at timestamp(6), updated_at timestamp(6) not null, withdrawn_at timestamp(6), id uuid not null, locked_by uuid, mentor_user_id uuid not null, previous_request_id uuid, reviewed_by uuid, terms_version varchar(80), method varchar(255) not null check (method in ('MANUAL','OCR','EMAIL_DOMAIN','ADMIN_INVITE')), rejection_reason TEXT, review_note TEXT, status varchar(255) not null check (status in ('DRAFT','PENDING_REVIEW','NEEDS_REVISION','APPROVED','REJECTED','WITHDRAWN')), submitted_note TEXT, primary key (id));
create table messages (created_at timestamp(6) not null, conversation_id uuid not null, id uuid not null, sender_id uuid, message_type varchar(50) not null check (message_type in ('TEXT','SYSTEM')), content TEXT not null, primary key (id));
create table notifications (created_at timestamp(6) not null, read_at timestamp(6), id uuid not null, recipient_user_id uuid not null, related_entity_id uuid, related_entity_type varchar(80), type varchar(100) not null check (type in ('MENTOR_VERIFICATION_APPROVED','MENTOR_VERIFICATION_REJECTED','MENTOR_VERIFICATION_NEEDS_REVISION','BOOKING_REQUEST_CREATED','BOOKING_ACCEPTED','BOOKING_PAYMENT_CONFIRMED','BOOKING_PAYMENT_EXPIRED','BOOKING_REJECTED','BOOKING_CANCELLED_BY_MENTEE','BOOKING_CANCELLED_BY_MENTOR','BOOKING_AUTO_REJECTED','BOOKING_REQUEST_EXPIRED','BOOKING_RESCHEDULE_REQUESTED','BOOKING_RESCHEDULE_ACCEPTED','BOOKING_RESCHEDULE_REJECTED','BOOKING_RESCHEDULE_EXPIRED','MEETING_LINK_UPDATED','SESSION_COMPLETED','FEEDBACK_RECEIVED','FORUM_POST_COMMENTED','FORUM_POST_HIDDEN','FORUM_COMMENT_HIDDEN','ACCOUNT_UNLOCKED')), title varchar(200) not null, message TEXT, primary key (id));
create table oauth_accounts (created_at timestamp(6) not null, updated_at timestamp(6) not null, id uuid not null, user_id uuid not null, provider varchar(50) not null, provider_email varchar(255), provider_user_id varchar(255) not null, primary key (id), constraint uq_oauth_accounts_provider_user unique (provider, provider_user_id));
create table payment_attempts (attempt_no integer not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, id uuid not null, payment_order_id uuid not null, status varchar(30) not null check (status in ('PENDING','REDIRECTED','SUCCEEDED','FAILED','CANCELLED','EXPIRED')), provider_status varchar(40), provider_event_id varchar(100) unique, provider_order_code varchar(100), provider_transaction_id varchar(100) unique, provider_payment_link_id varchar(120), checkout_url TEXT, failure_reason TEXT, primary key (id), constraint idx_payment_attempts_provider_order_code unique (provider_order_code));
create table payment_orders (campaign_credit_scoin integer not null, commission_rate_bps integer not null, commission_scoin integer not null, coupon_discount_scoin integer not null, gross_scoin integer not null, mentor_net_scoin integer not null, remaining_payable_scoin integer not null, user_credit_scoin integer not null, cancelled_at timestamp(6), created_at timestamp(6) not null, credit_finalized_at timestamp(6), expires_at timestamp(6), failed_at timestamp(6), paid_at timestamp(6), updated_at timestamp(6) not null, booking_id uuid not null unique, campaign_id uuid, coupon_id uuid, id uuid not null, mentor_user_id uuid not null, payer_user_id uuid not null, service_id uuid, campaign_funding_source varchar(30) check (campaign_funding_source in ('APP_FUNDED','MENTOR_FUNDED','MIXED')), payment_provider varchar(30) not null check (payment_provider in ('PAYOS')), status varchar(30) not null check (status in ('PENDING','PARTIALLY_COVERED_BY_CREDIT','AWAITING_PROVIDER_PAYMENT','PAID','FAILED','CANCELLED','EXPIRED')), provider_status varchar(40), order_code varchar(80) not null unique, coupon_code_snapshot varchar(100), provider_event_id varchar(100) unique, provider_order_code varchar(100) unique, provider_transaction_id varchar(100) unique, provider_payment_link_id varchar(120), campaign_name_snapshot varchar(150), payment_link TEXT, primary key (id));
create table payout_requests (amount_scoin integer not null, approved_at timestamp(6), created_at timestamp(6) not null, paid_at timestamp(6), rejected_at timestamp(6), requested_at timestamp(6) not null, reviewed_at timestamp(6), updated_at timestamp(6) not null, admin_user_id uuid, id uuid not null, mentor_user_id uuid not null, payout_profile_id uuid not null, settlement_account_id uuid not null, status varchar(20) not null check (status in ('REQUESTED','APPROVED','REJECTED','PAID','CANCELLED')), bank_account_number_masked_snapshot varchar(30) not null, bank_account_name_snapshot varchar(150) not null, bank_name_snapshot varchar(150) not null, admin_note TEXT, primary key (id));
create table session_feedbacks (is_public boolean not null, rating integer not null, satisfaction_level integer, would_recommend boolean, created_at timestamp(6) not null, updated_at timestamp(6) not null, booking_id uuid not null, id uuid not null, reviewee_user_id uuid not null, reviewer_user_id uuid not null, comment TEXT, primary key (id), constraint uq_session_feedbacks unique (booking_id, reviewer_user_id));
create table sessions (actual_end_time timestamp(6), actual_start_time timestamp(6), created_at timestamp(6) not null, scheduled_end_time timestamp(6) not null, scheduled_start_time timestamp(6) not null, updated_at timestamp(6) not null, id uuid not null, mentor_user_id uuid not null, service_id uuid, source_id uuid not null, source_type varchar(50) not null check (source_type in ('BOOKING','CLASS_OFFERING')), status varchar(50) not null check (status in ('SCHEDULED','IN_PROGRESS','COMPLETED','CANCELLED')), meeting_link TEXT, meeting_platform varchar(255) check (meeting_platform in ('GOOGLE_MEET','ZOOM','MICROSOFT_TEAMS','DISCORD','OFFLINE','OTHER')), primary key (id), constraint idx_sessions_source unique (source_type, source_id));
create table settlement_accounts (active boolean not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, id uuid not null, owner_id uuid, owner_type varchar(40) not null check (owner_type in ('USER_CREDIT','MENTOR_SETTLEMENT','PLATFORM_SETTLEMENT')), account_code varchar(120) not null unique, primary key (id), constraint idx_settlement_accounts_owner unique (owner_type, owner_id));
create table settlement_entries (amount_scoin integer not null, balance_effect_scoin integer not null, commission_rate_bps integer, commission_scoin integer, gross_scoin integer, mentor_net_scoin integer, created_at timestamp(6) not null, account_id uuid not null, id uuid not null, source_id uuid, entry_type varchar(30) not null check (entry_type in ('RELEASE','HOLD','PAID_OUT','COMMISSION','ADJUSTMENT','VOID')), source_type varchar(40) not null check (source_type in ('PAYMENT_ORDER','BOOKING','CAMPAIGN','COUPON','MANUAL','PAYOUT_REQUEST','REFUND')), memo TEXT, primary key (id));
create table specialization_tags (specialization_id uuid not null, tag_id uuid not null, primary key (specialization_id, tag_id));
create table specializations (is_active boolean not null, is_expected boolean not null, id uuid not null, program_id uuid not null, code varchar(50) not null unique, name_en varchar(200), name_vi varchar(200) not null, primary key (id));
create table student_profiles (graduation_year integer, intake_year integer, is_alumni boolean not null, semester integer, created_at timestamp(6) not null, updated_at timestamp(6) not null, campus_id uuid, program_id uuid, specialization_id uuid, user_id uuid not null, student_code varchar(30), bio TEXT, primary key (user_id));
create table tags (is_fixed boolean not null, weight integer not null, approved_at timestamp(6), created_at timestamp(6) not null, updated_at timestamp(6) not null, approved_by uuid, created_by uuid, id uuid not null, parent_tag_id uuid, code varchar(80) not null unique, name_en varchar(150), name_vi varchar(150) not null, status varchar(255) not null check (status in ('ACTIVE','INACTIVE','PENDING_REVIEW','REJECTED')), type varchar(255) not null check (type in ('MAJOR','SPECIALIZATION','TECH_SKILL','BUSINESS_SKILL','LANGUAGE','CAREER','SOFT_SKILL','TOOL','INDUSTRY','HELP_TOPIC')), primary key (id));
create table user_learning_goals (priority integer not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, id uuid not null, tag_id uuid, user_id uuid not null, goal_title varchar(200) not null, goal_description TEXT, primary key (id));
create table user_roles (user_id uuid not null, role varchar(255) check (role in ('MENTEE','MENTOR','ADMIN','SYSTEM_ADMIN')));
create table user_sessions (is_revoked boolean not null, created_at timestamp(6) not null, expires_at timestamp(6) not null, id uuid not null, user_id uuid not null, ip_address varchar(100), device_info TEXT, refresh_token_hash TEXT not null, primary key (id));
create table users (date_of_birth date, created_at timestamp(6) not null, deleted_at timestamp(6), last_login_at timestamp(6), updated_at timestamp(6) not null, id uuid not null, phone varchar(30), full_name varchar(150) not null, avatar_url TEXT, email varchar(255) not null unique, gender varchar(255) check (gender in ('MALE','FEMALE','OTHER','PREFER_NOT_TO_SAY')), status varchar(255) not null check (status in ('ACTIVE','INACTIVE','BANNED','DELETED')), primary key (id));
create index idx_admin_notes_target on admin_notes (target_type, target_id);
create index idx_admin_notes_admin_id on admin_notes (admin_user_id);
create index idx_audit_logs_actor_id on audit_logs (actor_user_id);
create index idx_audit_logs_action on audit_logs (action);
create index idx_audit_logs_entity on audit_logs (entity_type);
create index idx_audit_logs_created_at on audit_logs (created_at);
create index idx_bookings_mentee_id on bookings (mentee_user_id);
create index idx_bookings_mentor_id on bookings (mentor_user_id);
create index idx_bookings_status on bookings (status);
create index idx_bookings_start_time on bookings (selected_start_time);
create index idx_bookings_mentee_status_time on bookings (mentee_user_id, status, selected_start_time);
create index idx_bookings_mentor_status_time on bookings (mentor_user_id, status, selected_start_time);
create index idx_bookings_status_selected_start_time on bookings (status, selected_start_time);
create index idx_bookings_mentee_status_selected_time on bookings (mentee_user_id, status, selected_start_time, selected_end_time);
create index idx_campaigns_status on campaigns (status);
create index idx_campaigns_time_window on campaigns (start_at, end_at);
create index idx_conv_participants_user on conversation_participants (user_id);
create index idx_conversations_last_message_at on conversations (last_message_at);
create index idx_coupon_redemptions_coupon_id on coupon_redemptions (coupon_id);
create index idx_coupon_redemptions_user_id on coupon_redemptions (redeemer_user_id);
create index idx_coupons_status on coupons (status);
create index idx_coupons_time_window on coupons (start_at, end_at);
create index idx_credit_entries_account on credit_ledger_entries (account_id);
create index idx_credit_entries_source on credit_ledger_entries (source_type, source_id);
create index idx_credit_entries_origin on credit_ledger_entries (origin_type);
create index idx_email_outbox_to on email_outbox (to_email);
create index idx_email_outbox_status on email_outbox (status);
create index idx_email_outbox_created on email_outbox (created_at);
create index idx_files_owner_id on files (owner_id);
create index idx_files_purpose on files (purpose);
create index idx_availability_rules_mentor_active on mentor_availability_rules (mentor_user_id, is_active);
create index idx_availability_rules_date_range on mentor_availability_rules (effective_from, effective_to);
create index idx_availability_rules_repeat_type on mentor_availability_rules (repeat_type);
create index idx_availability_mentor_id on mentor_availability_slots (mentor_user_id);
create index idx_availability_start_time on mentor_availability_slots (start_time);
create index idx_availability_end_time on mentor_availability_slots (end_time);
create index idx_availability_booked on mentor_availability_slots (is_booked);
create index idx_availability_active on mentor_availability_slots (is_active);
create index idx_mentor_payout_profiles_mentor on mentor_payout_profiles (mentor_user_id);
create index idx_mentor_payout_profiles_default on mentor_payout_profiles (mentor_user_id, is_default);
create index idx_mentor_payout_profiles_active on mentor_payout_profiles (mentor_user_id, is_active);
create index idx_mentor_profiles_status on mentor_profiles (status);
create index idx_mentor_profiles_avg_rating on mentor_profiles (average_rating);
create index idx_mentor_profiles_available on mentor_profiles (is_available);
create index idx_mentor_profiles_teaching_mode on mentor_profiles (teaching_mode);
create index idx_mentor_profiles_booking_suspended_until on mentor_profiles (booking_suspended_until);
create index idx_mentor_services_mentor_id on mentor_services (mentor_user_id);
create index idx_mentor_services_active on mentor_services (is_active);
create index idx_mentor_tags_tag_primary on mentor_tags (tag_id, is_primary);
create index idx_mentor_tags_mentor_type on mentor_tags (mentor_user_id, tag_type);
create index idx_mentor_verification_documents_request_id on mentor_verification_documents (request_id);
create index idx_mentor_verification_documents_request_type on mentor_verification_documents (request_id, document_type);
create index idx_mentor_verification_documents_request_type_active on mentor_verification_documents (request_id, document_type, is_active);
create index idx_mentor_verification_event_request_created_at on mentor_verification_request_events (request_id, created_at);
create index idx_mentor_verification_event_type on mentor_verification_request_events (event_type);
create index idx_mentor_verification_mentor_id on mentor_verification_requests (mentor_user_id);
create index idx_mentor_verification_status on mentor_verification_requests (status);
create index idx_mentor_verification_method on mentor_verification_requests (method);
create index idx_mentor_verification_status_submitted_at on mentor_verification_requests (status, submitted_at);
create index idx_mentor_verification_status_submitted_at_id on mentor_verification_requests (status, submitted_at, id);
create index idx_mentor_verification_mentor_status on mentor_verification_requests (mentor_user_id, status);
create index idx_messages_conversation on messages (conversation_id);
create index idx_messages_sender on messages (sender_id);
create index idx_messages_created_at on messages (created_at);
create index idx_messages_conversation_created_at on messages (conversation_id, created_at);
create index idx_notifications_recipient_created on notifications (recipient_user_id, created_at desc);
create index idx_notifications_recipient_read on notifications (recipient_user_id, read_at);
create index idx_oauth_accounts_user_id on oauth_accounts (user_id);
create index idx_payment_attempts_order_id on payment_attempts (payment_order_id);
create index idx_payment_attempts_status on payment_attempts (status);
create index idx_payment_orders_payer_id on payment_orders (payer_user_id);
create index idx_payment_orders_status on payment_orders (status);
create index idx_payout_requests_mentor_id on payout_requests (mentor_user_id);
create index idx_payout_requests_status on payout_requests (status);
create index idx_payout_requests_settlement_account on payout_requests (settlement_account_id);
create index idx_feedbacks_reviewee_id on session_feedbacks (reviewee_user_id);
create index idx_feedbacks_rating on session_feedbacks (rating);
create index idx_sessions_mentor_id on sessions (mentor_user_id);
create index idx_sessions_status on sessions (status);
create index idx_settlement_entries_account on settlement_entries (account_id);
create index idx_settlement_entries_source on settlement_entries (source_type, source_id);
create index idx_spec_tags_tag_id on specialization_tags (tag_id);
create index idx_specializations_program_active on specializations (program_id, is_active);
create index idx_student_profiles_campus_id on student_profiles (campus_id);
create index idx_student_profiles_program_id on student_profiles (program_id);
create index idx_student_profiles_spec_id on student_profiles (specialization_id);
create index idx_tags_type on tags (type);
create index idx_tags_status on tags (status);
create index idx_tags_parent_id on tags (parent_tag_id);
create index idx_user_goals_user_id on user_learning_goals (user_id);
create index idx_user_goals_tag_id on user_learning_goals (tag_id);
create index idx_user_sessions_user_id on user_sessions (user_id);
create index idx_user_sessions_token on user_sessions (refresh_token_hash);
create index idx_users_status on users (status);
create index idx_users_full_name on users (full_name);
alter table if exists admin_notes add constraint fk_admin_notes_admin foreign key (admin_user_id) references users;
alter table if exists audit_logs add constraint fk_audit_logs_actor foreign key (actor_user_id) references users;
alter table if exists availability_slot_services add constraint fk_availability_slot_services_service foreign key (service_id) references mentor_services;
alter table if exists availability_slot_services add constraint fk_availability_slot_services_slot foreign key (slot_id) references mentor_availability_slots;
alter table if exists bookings add constraint fk_bookings_mentee foreign key (mentee_user_id) references users;
alter table if exists bookings add constraint fk_bookings_mentor foreign key (mentor_user_id) references mentor_profiles;
alter table if exists bookings add constraint fk_bookings_service foreign key (service_id) references mentor_services;
alter table if exists bookings add constraint fk_bookings_slot foreign key (slot_id) references mentor_availability_slots;
alter table if exists campaign_audience_campus_ids add constraint FK3kw8ahj3w2yshu8bebedpdvue foreign key (campaign_id) references campaigns;
alter table if exists campaign_audience_help_topic_ids add constraint FKo69rcwkdih337u0j3giao02ms foreign key (campaign_id) references campaigns;
alter table if exists campaign_audience_program_ids add constraint FK2n9x96hfvxgmcdfh93cwuw8c4 foreign key (campaign_id) references campaigns;
alter table if exists campaign_audience_role_codes add constraint FKllgqu7tv101puqehondx7vmpw foreign key (campaign_id) references campaigns;
alter table if exists campaign_audience_specialization_ids add constraint FKr2hccj2lt6w3r7olp249h9pi5 foreign key (campaign_id) references campaigns;
alter table if exists campaign_benefits add constraint FKlxp62mjytgnakyo30ws72wi5l foreign key (campaign_id) references campaigns;
alter table if exists conversation_participants add constraint fk_conv_participants_conv foreign key (conversation_id) references conversations;
alter table if exists conversation_participants add constraint fk_conv_participants_user foreign key (user_id) references users;
alter table if exists coupon_applicable_help_topic_ids add constraint FK2ey6frmvhu4715e86cuv7ajbc foreign key (coupon_id) references coupons;
alter table if exists coupon_applicable_mentor_ids add constraint FKk9wnxro7aikrli17jff1djtma foreign key (coupon_id) references coupons;
alter table if exists coupon_applicable_service_ids add constraint FKl4xh9ndb9fndhrbbk5dlhwmpj foreign key (coupon_id) references coupons;
alter table if exists files add constraint fk_files_owner foreign key (owner_id) references users;
alter table if exists mentor_availability_rules add constraint fk_availability_rules_mentor foreign key (mentor_user_id) references mentor_profiles;
alter table if exists mentor_availability_slots add constraint fk_availability_mentor foreign key (mentor_user_id) references mentor_profiles;
alter table if exists mentor_availability_slots add constraint fk_availability_rule foreign key (rule_id) references mentor_availability_rules;
alter table if exists mentor_profiles add constraint fk_mentor_profiles_verifier foreign key (verified_by) references users;
alter table if exists mentor_profiles add constraint fk_mentor_profiles_user foreign key (user_id) references users;
alter table if exists mentor_service_help_topics add constraint fk_service_help_topics_tag foreign key (tag_id) references tags;
alter table if exists mentor_service_help_topics add constraint fk_service_help_topics_service foreign key (service_id) references mentor_services;
alter table if exists mentor_services add constraint fk_mentor_services_mentor foreign key (mentor_user_id) references mentor_profiles;
alter table if exists mentor_tags add constraint fk_mentor_tags_mentor foreign key (mentor_user_id) references mentor_profiles;
alter table if exists mentor_tags add constraint fk_mentor_tags_tag foreign key (tag_id) references tags;
alter table if exists mentor_verification_documents add constraint fk_mentor_verification_documents_request foreign key (request_id) references mentor_verification_requests;
alter table if exists mentor_verification_documents add constraint fk_mentor_verification_documents_file foreign key (stored_file_id) references files;
alter table if exists mentor_verification_documents add constraint fk_mentor_verification_documents_uploaded_by foreign key (uploaded_by_user_id) references users;
alter table if exists mentor_verification_request_events add constraint fk_mentor_verification_event_actor foreign key (actor_user_id) references users;
alter table if exists mentor_verification_request_events add constraint fk_mentor_verification_event_request foreign key (request_id) references mentor_verification_requests;
alter table if exists mentor_verification_requests add constraint fk_mentor_verification_locked_by foreign key (locked_by) references users;
alter table if exists mentor_verification_requests add constraint fk_mentor_verification_mentor foreign key (mentor_user_id) references users;
alter table if exists mentor_verification_requests add constraint fk_mentor_verification_previous foreign key (previous_request_id) references mentor_verification_requests;
alter table if exists mentor_verification_requests add constraint fk_mentor_verification_reviewer foreign key (reviewed_by) references users;
alter table if exists messages add constraint fk_messages_conversation foreign key (conversation_id) references conversations;
alter table if exists messages add constraint fk_messages_sender foreign key (sender_id) references users;
alter table if exists notifications add constraint fk_notifications_recipient foreign key (recipient_user_id) references users;
alter table if exists oauth_accounts add constraint fk_oauth_accounts_user foreign key (user_id) references users;
alter table if exists session_feedbacks add constraint fk_feedbacks_booking foreign key (booking_id) references bookings;
alter table if exists session_feedbacks add constraint fk_feedbacks_reviewee foreign key (reviewee_user_id) references users;
alter table if exists session_feedbacks add constraint fk_feedbacks_reviewer foreign key (reviewer_user_id) references users;
alter table if exists sessions add constraint fk_sessions_mentor foreign key (mentor_user_id) references users;
alter table if exists sessions add constraint fk_sessions_service foreign key (service_id) references mentor_services;
alter table if exists specialization_tags add constraint fk_spec_tags_spec foreign key (specialization_id) references specializations;
alter table if exists specialization_tags add constraint fk_spec_tags_tag foreign key (tag_id) references tags;
alter table if exists specializations add constraint fk_specializations_program foreign key (program_id) references academic_programs;
alter table if exists student_profiles add constraint fk_student_profiles_campus foreign key (campus_id) references campuses;
alter table if exists student_profiles add constraint fk_student_profiles_program foreign key (program_id) references academic_programs;
alter table if exists student_profiles add constraint fk_student_profiles_spec foreign key (specialization_id) references specializations;
alter table if exists student_profiles add constraint fk_student_profiles_user foreign key (user_id) references users;
alter table if exists tags add constraint fk_tags_approver foreign key (approved_by) references users;
alter table if exists tags add constraint fk_tags_creator foreign key (created_by) references users;
alter table if exists tags add constraint fk_tags_parent foreign key (parent_tag_id) references tags;
alter table if exists user_learning_goals add constraint fk_user_goals_tag foreign key (tag_id) references tags;
alter table if exists user_learning_goals add constraint fk_user_goals_user foreign key (user_id) references users;
alter table if exists user_roles add constraint fk_user_roles_user foreign key (user_id) references users;
alter table if exists user_sessions add constraint fk_user_sessions_user foreign key (user_id) references users;
